name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "dev"
    env:
      CONTAINER_REGISTRY_ENDPOINT: rg.${{ vars.SCALEWAY_REGION }}.scw.cloud/${{ vars.ENV_NAME }}_container_registry
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          registry: ${{ env.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the Docker image
        run: docker build . -t $CONTAINER_REGISTRY_ENDPOINT/my-nginx:latest
        working-directory: ./app

      - name: Push the Docker Image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/my-nginx:latest
